# Risk Customer Project

## Business Problem

This dataset consists of 20 features of the customers.
It could be used to predict if the customer could be given credit.
Many features require data cleaning.
This is a great dataset for practicing data cleaning and feature engineering and building a binary classification model.

# 1. Import Data

In [4]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

path = '/Users/mac/Desktop/Project/risk_customer/credit_customers.csv'

df = pd.read_csv(path)
df.head()

,checking_status,duration,credit_history,purpose,credit_amount,savings_status,employment,installment_commitment,personal_status,other_parties,...,property_magnitude,age,other_payment_plans,housing,existing_credits,job,num_dependents,own_telephone,foreign_worker,class
0,<0,6.0,critical/other existing credit,radio/tv,1169.0,no known savings,>=7,4.0,male single,none,...,real estate,67.0,none,own,2.0,skilled,1.0,yes,yes,good
1,0<=X<200,48.0,existing paid,radio/tv,5951.0,<100,1<=X<4,2.0,female div/dep/mar,none,...,real estate,22.0,none,own,1.0,skilled,1.0,none,yes,bad
2,no checking,12.0,critical/other existing credit,education,2096.0,<100,4<=X<7,2.0,male single,none,...,real estate,49.0,none,own,1.0,unskilled resident,2.0,none,yes,good
3,<0,42.0,existing paid,furniture/equipment,7882.0,<100,4<=X<7,2.0,male single,guarantor,...,life insurance,45.0,none,for free,1.0,skilled,2.0,none,yes,good
4,<0,24.0,delayed previously,new car,4870.0,<100,1<=X<4,3.0,male single,none,...,no known property,53.0,none,for free,2.0,skilled,2.0,none,yes,bad

### Data Dictionary¶
Since the origin of the dataset in kaggle had few and shallow descriptions of the data. Therefore, we had to delve into the world of credit risk to be able to define the meaning of each of the features. The dataset have the following columns:

checking_status: The currently balance account.

duration: duration of the credit payment, in months.

credit_history: Is the customer credit history. It can have the following values:

existing paid: currently credit process
all paid: all the credit abre paid by the customer
delayed previously: past delays at # the credit payment
critical/ other existing credit: critical credit accounts
no credits/ all paid: customer that never gets credit.
purpose: porpouse of the credit requested.

credit_amount: Amount of the credit requested

savings_status: Balance account of savings/ bond.

employment:How many years the customer has employed.

installment_commitment: Percentual that the customer cannot reach due to the income. When a customer takes a credit, the installment cannot ultrapass a percentual of customer income.

personal_status: if is divorced, married, etc.

other_parties: Another part involde on th credit, like guarantos ("fiador").

residence_since: How many year the customer has in the country.

property_magnitude: The good of the customer.

age: The age of the customer.

other_payment_plans: If the customer has another credit line and how the type (store, bank, etc).

housing:The housing customer type, could be own, for free or rent.

existing_credits: Number of existing credits at this bank.

job: This represents whats type of job the customer has. Could be skilled, unskilled resident, high qualif/self emp/mgmt and unemp/unskilled non res.

num_dependents: The number of depedents that live wth the customer.

own_telephone: If the customer has a telephone.

foreign_worker: If the customer is a foreign or not.

class: Our target. If the credit is goos or bad to the bank.

In [8]:
df.shape

(1000, 21)

In [12]:
df_info = pd.DataFrame(df.dtypes,columns = ['dtypes'])
df_info['unique'] = df.nunique().values
df_info['null'] = df.isnull().sum().values
print(df_info)

                         dtypes  unique  null
checking_status          object       4     0
duration                float64      33     0
credit_history           object       5     0
purpose                  object      10     0
credit_amount           float64     921     0
savings_status           object       5     0
employment               object       5     0
installment_commitment  float64       4     0
personal_status          object       4     0
other_parties            object       3     0
residence_since         float64       4     0
property_magnitude       object       4     0
age                     float64      53     0
other_payment_plans      object       3     0
housing                  object       3     0
existing_credits        float64       4     0
job                      object       4     0
num_dependents          float64       2     0
own_telephone            object       2     0
foreign_worker           object       2     0
class                    object       2     0